name: Vercel Node.js Deployment
env:
  # Project information stored in GitHub Secrets
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Pull Vercel environment information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy the project to Vercel
      - name: Deploy Project
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
